### ISSUE TITLE
[ErrorResponseException] 10062: Unknown interaction (Show Modal In JDA) 

### ISSUE THREAD

**Issue by YuInseo** [discord-jda/JDA#2548]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have checked for PRs that might already address this issue.

### Version of JDA

5.0.0-beta.13

### Expected Behaviour

Is there something problem in my code? 
I've got an error so randomly 

`
 @Override
    public void onButtonInteraction(@NotNull ButtonInteractionEvent event) {

        TextInput textInput = TextInput.create("text-input","text", TextInputStyle.PARAGRAPH).build();
        Modal modal = Modal.create("custom-modal", "modal")
                .addComponents(ActionRow.of(textInput))
                .build();

        event.replyModal(modal).queue();
    }
`

I edit it 

`
    @Override
    public void onButtonInteraction(@NotNull ButtonInteractionEvent event) {

        TextInput textInput = TextInput.create("text-input","text", TextInputStyle.PARAGRAPH).build();
        Modal modal = Modal.create("custom-modal", "modal")
                .addComponents(ActionRow.of(textInput))
                .build();

        event.getInteraction().replyModal(modal).queue();
    }
`

But, Both not work neither sometimes

 

### Code Example for Reproduction Steps

```java
@Override
    public void onButtonInteraction(@NotNull ButtonInteractionEvent event) {

        TextInput textInput = TextInput.create("text-input","text", TextInputStyle.PARAGRAPH).build();
        Modal modal = Modal.create("custom-modal", "modal")
                .addComponents(ActionRow.of(textInput))
                .build();

        event.getInteraction().replyModal(modal).queue();
    }
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder builder = JDABuilder.createDefault(BOT_TOKEN);
```

### Exception or Error

```yesyes
22:26:50.069 [ForkJoinPool.commonPool-worker-1] ERROR n.d.jda.api.requests.RestAction - RestAction queue returned failure: [ErrorResponseException] 10062: Unknown interaction
net.dv8tion.jda.api.exceptions.ContextException: null
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:77)
        at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197)
        at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.queue(InteractionCallbackImpl.java:74)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538)
        at kr.starly.discordbot.listener.ticket.TicketRequestButtonInteraction.onButtonInteraction(TicketRequestButtonInteraction.java:36)
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:442)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:176)
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleAction(InteractionCreateHandler.java:148)
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:100)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1014)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:900)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:878)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1053)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by MinnDevelopment** [comment]
As suggested by the [troubleshooting guide](https://jda.wiki/using-jda/troubleshooting/#this-interaction-failed-unknown-interaction):

> ### This interaction failed / Unknown Interaction
> This means you didn't acknowledge or reply to an interaction in time. You only have 3 seconds to reply or acknowledge. You have to use event.deferReply().queue(), event.deferEdit().queue(), event.editMessage(...).queue(), or event.reply(...).queue(). (If you don't queue() it won't do it)


Either you have a second instance of your bot running that already replied (common problem with eclipse users), or you took longer than 3 seconds to reply to the interaction.

**Comment by YuInseo** [comment]
> As suggested by the [troubleshooting guide](https://jda.wiki/using-jda/troubleshooting/#this-interaction-failed-unknown-interaction):
> 
> > ### This interaction failed / Unknown Interaction
> > This means you didn't acknowledge or reply to an interaction in time. You only have 3 seconds to reply or acknowledge. You have to use event.deferReply().queue(), event.deferEdit().queue(), event.editMessage(...).queue(), or event.reply(...).queue(). (If you don't queue() it won't do it)
> 
> Either you have a second instance of your bot running that already replied (common problem with eclipse users), or you took longer than 3 seconds to reply to the interaction.

The former Is not But, I wonder in latter Why It's take more than 3 seconds? even just a simple code

**Comment by YuInseo** [comment]
> Go reset your token and try again, this will make previous instances not reply anymore.
> 
> Also when asked about your `JDABuilder`, we need you to supply the entire builder, including listeners and the `build()` call

Oh sorry about that I didn't know it's require entire builder 'cause This is my first post 
Soo That's mean a limitation exist on it? (If it's true)

Did you know any expected number of limitation ?

**Comment by Andre601** [comment]
Please provide the things requested.

**Comment by freya022** [comment]
Also code blocks are made as:
\`\`\`java
//Code
\`\`\`

I cannot answer your question about limitations if you don't provide your configuration (your entire `JDABuilder` basically)

**Comment by YuInseo** [comment]
> Also code blocks are made as: ```java //Code ```
> 
> I cannot answer your question about limitations if you don't provide your configuration (your entire `JDABuilder` basically)

Sorrry for late  I jsut edit it!

**Comment by freya022** [comment]
Seems fine, you just have another instance running, go reset your token

You don't need `getInteraction()` calls btw, using the event is just as fine

**Comment by YuInseo** [comment]
> Seems fine, you just have another instance running, go reset your token
> 
> You don't need `getInteraction()` calls btw, using the event is just as fine, I would also recommend adding the event listeners on `JDABuilder` instead of `JDA`

Thank ur solution I'll edit it and btw, What if that model show in many time by user? 
Is it able to prevent with the "try&catch" keywords?

**Comment by freya022** [comment]
You cannot reply multiple times, and you cannot send multiple modals

If you need a multi-step modal then make a button that will show the next modal when clicked

If you want to prevent an user for using the button more than once then edit it to either remove it, or disable it
You would need to reply the modal and then use the hook to "edit the original components" with the new buttons
