### ISSUE TITLE
member.canInteract()

### ISSUE THREAD

**Issue by Izocel** [discord-jda/JDA#2566]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have checked for PRs that might already address this issue.

### Version of JDA

4.4.1_353

### Expected Behaviour

`Return false` to prevent the kick tentative since the roles don't match or both members params are the same member.

### Code Example for Reproduction Steps

```java
if (member.canInteract(lookUpMember)) {
                try {
                    lookUpMember.kick();
                } catch (Exception e) {
                    sb.append("⚠️ [Discord-Kick] " + e.getMessage() + "\n\n");
                    tx.setData("error-state", "error discord-kick unauthorized (higher or equal ranks)");
                    SentryService.captureEx(e);
                }
            }
            else {
                sb.append("⚠️ [Discord-Kick] Can't modify a member with higher or equal highest role than yourself!\n\n");
            }
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
public void connect() {
        ISpan process = plugin.getSentryService().findWithuniqueName("onEnable")
                .startChild("DiscordManager.connect");
        try {
            final String token = this.configs.get("discordBotToken", null);
            this.logger.info("JDA TOKEN: " + token.substring(0, 56) + "************");

            jda = JDABuilder.create(token, EnumSet.allOf(GatewayIntent.class))
                    .build()
                    .awaitReady();

            this.checkGuild();
            this.plugin.getSentryService().setUsername(this.ownerId);
            this.plugin.getSentryService().setUserId(this.getGuild().getId());

            if (jda == null) {
                throw new LoginException("Cannot initialize JDA");
            }

        } catch (LoginException | InterruptedException e) {
            process.setThrowable(e);
            process.setStatus(SpanStatus.INTERNAL_ERROR);
            SentryService.captureEx(e);
            Bukkit.shutdown();
        }

        process.setStatus(SpanStatus.OK);
        process.finish();
    }
```

### Exception or Error

```yesyes
[20:41:53 WARN]: [WDMC-Sentry] WARNING:
[20:41:53 WARN]: net.dv8tion.jda.api.exceptions.HierarchyException: Can't modify a member with higher or equal highest role than yourself!
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//services.sentry.SentryService.captureEx(SentryService.java:149)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//commands.discords.DeleteUserDbCmd.execute(DeleteUserDbCmd.java:137)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//commands.discords.UserOnlyCmd.onSlashCommand(UserOnlyCmd.java:51)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:160)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:75)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:59)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[20:41:53 WARN]:        at WhitelistDmc-2023.7.20231017-shaded.jar//com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
>
```

**Comment by MinnDevelopment** [comment]
What is `member`? Why does this stacktrace not come from JDA?

**Comment by duncte123** [comment]
Who is `member` in this context? Is it the bot or the user that ran the command?

**Comment by Izocel** [comment]
Member is the user taht ranthe cmd
Lookupmember is a cmd parameter

**Comment by Izocel** [comment]
> What is `member`? Why does this stacktrace not come from JDA?

Because i use JDA in my lrogram ?

**Comment by duncte123** [comment]
> Member is the user that ran the cmd
> Lookupmember is a cmd parameter 

While the user may be able to interact, your bot cannot. You should also check if the bot can interact (getSelfMember on a guild)

**Comment by Izocel** [comment]
> > Member is the user that ran the cmd
> > Lookupmember is a cmd parameter 
> 
> While the user may be able to interact, your bot cannot. You should also check if the bot can interact (getSelfMember on a guild)

Thats true but my bot is administrator

**Comment by Skullition** [comment]
> Thats true but my bot is administrator

Have you checked your guild hierarchy?

**Comment by Andre601** [comment]
> Thats true but my bot is administrator

That doesn't matter. If the member you want to interact with has a role higher or equal to your bot will this fail from what I know. Admin or not.
(Also, personal recommendation is to not just give admin. It's a lazy aproach that exposes your bot to abuse.)

**Comment by Izocel** [comment]
> getSelfMember

I know I do that in dev mode but users manages there own bot based on my code anyway so its up to them

**Comment by Andre601** [comment]
> I know I do that in dev mode but users manages there own bot based on my code anyway so its up to them

That... would still be the right aproach? `getSelfMember` gets the current account used for the bot, so if they run their own instance, this would return whatever account they have.
This isn't some hardcoded account or other value...

**Comment by Izocel** [comment]
@Andre601  check last comment 'edited' now no error the kick did not throw but the member is still in the voice channel

**Comment by Izocel** [comment]
should i use kick().complete() ???

**Comment by Izocel** [comment]
Yes it was juste the .complet() thanks guys ;)
