### ISSUE TITLE
Exception in WS read thread: RSV1 bit of a frame is set unexpectedly

### ISSUE THREAD

**Issue by freya022** [discord-jda/JDA#2663]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have checked for PRs that might already address this issue.

### Version of JDA

5.0.0-beta.18

### Expected Behaviour

Handle the frame gracefully I guess?

### Code Example for Reproduction Steps

```java
N/A
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder.createLight(token)
            .enableIntents(GatewayIntent.MESSAGE_CONTENT)
            .setActivity(Activity.customStatus("I need more bullets"))
            .setEventManager(/* */)
            .build()
```

### Exception or Error

```yesyes
08:23:31.148 JDA MainWS-ReadThread      n.d.j.i.requests.WebSocketClient     #onError                  L1113  WebSocketClient      ERROR  There was an error in the WebSocket connection
com.neovisionaries.ws.client.WebSocketException: The RSV1 bit of a frame is set unexpectedly.
	at com.neovisionaries.ws.client.ReadingThread.verifyReservedBit1(ReadingThread.java:481)
	at com.neovisionaries.ws.client.ReadingThread.verifyReservedBits(ReadingThread.java:451)
	at com.neovisionaries.ws.client.ReadingThread.verifyFrame(ReadingThread.java:421)
	at com.neovisionaries.ws.client.ReadingThread.readFrame(ReadingThread.java:341)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:99)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

## BEFORE REPORTING A SIMILAR ERROR

Please update to the JDA snapshot https://github.com/discord-jda/JDA/issues/2663#issuecomment-2091841521 and include the WebSocket trace with the error

**Comment by MinnDevelopment** [comment]
The latest master commit added a new trace information to further investigate this issue, please let me know when you encounter the error including that trace detail.

**Comment by freya022** [comment]
This is not an issue on startup, it happens at random times, days after the bot started, multiple people have reported this issue, I've created this issue for tracking purpose, so it can also be linked when a fix is available

**Comment by duncte123** [comment]
Got one running main: https://duncte123.sentry.io/share/issue/fac5e12d2d2c40bc8baa0a46f21fc64f/

**Comment by rakosi2** [comment]
Got one running 5.0.0-beta.23

**Comment by freya022** [comment]
> Got one running 5.0.0-beta.23

Please send the exception with the WS trace, like duncte123 sent

**Comment by rakosi2** [comment]
I don't think I have WS trace enabled or how to retrieve it. I have the stacktrace that is the same as the OP
`[2024/05/02 23:20:23] [ERROR] [JDA MainWS-ReadThread] ERROR WebSocketClient - There was an error in the WebSocket connection
com.neovisionaries.ws.client.WebSocketException: The RSV1 bit of a frame is set unexpectedly.
	at com.neovisionaries.ws.client.ReadingThread.verifyReservedBit1(ReadingThread.java:481)
	at com.neovisionaries.ws.client.ReadingThread.verifyReservedBits(ReadingThread.java:451)
	at com.neovisionaries.ws.client.ReadingThread.verifyFrame(ReadingThread.java:421)
	at com.neovisionaries.ws.client.ReadingThread.readFrame(ReadingThread.java:341)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:99)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
[2024/05/02 23:20:23] [ERROR] Exception while handling JDA event::
com.neovisionaries.ws.client.WebSocketException: The RSV1 bit of a frame is set unexpectedly.
	at com.neovisionaries.ws.client.ReadingThread.verifyReservedBit1(ReadingThread.java:481)
	at com.neovisionaries.ws.client.ReadingThread.verifyReservedBits(ReadingThread.java:451)
	at com.neovisionaries.ws.client.ReadingThread.verifyFrame(ReadingThread.java:421)
	at com.neovisionaries.ws.client.ReadingThread.readFrame(ReadingThread.java:341)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:99)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)`

**Comment by freya022** [comment]
Ah yea, please updated to the latest snapshot:

Maven:
```xml
<repositories>
    <repository>
        <id>jitpack</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>io.github.discord-jda</groupId>
        <artifactId>JDA</artifactId>
        <version>6f7189f91a</version>
    </dependency>
</dependencies>
```

Gradle (Kotlin):
```kt
repositories {
    mavenCentral()
    maven("https://jitpack.io")
}

dependencies {
    implementation("io.github.discord-jda:JDA:6f7189f91a")
}
```

**Comment by rakosi2** [comment]
I have updated my POM, will see if I get it again. https://github.com/Slaynash/Lumbot/commit/d30becdef1d36d21bbf3d425a7fd18ba68fb8ed5

**Comment by MinnDevelopment** [comment]
This issue has been escalated to cloudflare. Apparently, the web socket is receiving an http response body instead of a web socket frame. The specific bit happens to be set when the frame starts with `HTTP/1.1 502 Bad Gateway Server`.

**Comment by MinnDevelopment** [comment]
This should be fixed as of last Friday.
