### ISSUE TITLE
Sending message with null message reference leads to an error

### ISSUE THREAD

**Issue by MandarinSmell** [discord-jda/JDA#2750]
### General Troubleshooting

- [x] I have checked for similar issues on the Issue-tracker.
- [X] I have checked for PRs that might already address this issue.

### Version of JDA

5.1.2

### Expected Behaviour

When using `setMessageReference` method in `MessageCreateAction`, you can pass `null` as a value because the parameter is annotated with `Nullable`. Before 5.1.2, this worked without any problems, but since 5.1.2, when you pass `null` as parameter, it throws an exception. Cause of an error can be related with new feature of message forwarding

### Code Example for Reproduction Steps

```java
public void test() {
  MessageChannel channel = getChannel();

  // Yes, it's weird to pass null here, but this is purely for reproduction of the error
  channel.sendMessage("Test Content").setMessageReference((Message) null).queue();
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
DefaultShardManagerBuilder builder = DefaultShardManagerBuilder.createDefault(TOKEN);

builder.setEnabledIntents(
        GatewayIntent.GUILD_MEMBERS, 
        GatewayIntent.GUILD_EMOJIS_AND_STICKERS, 
        GatewayIntent.GUILD_MESSAGES, 
        GatewayIntent.GUILD_MESSAGE_REACTIONS, 
        GatewayIntent.DIRECT_MESSAGES, 
        GatewayIntent.DIRECT_MESSAGE_REACTIONS, 
        GatewayIntent.MESSAGE_CONTENT, 
        GatewayIntent.SCHEDULED_EVENTS
);

builder.disableCache(CacheFlag.VOICE_STATE);
builder.setActivity(Activity.playing(normal));
builder.addEventListeners(new AllEventAdapter());

ShardManager client = builder.build();
```

### Exception or Error

```yesyes
net.dv8tion.jda.api.exceptions.ErrorResponseException: 50035: Invalid Form Body
message_reference.message_id
	- BASE_TYPE_REQUIRED: This field is required
	at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:201) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.api.requests.Request.createErrorResponseException(Request.java:157) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:290) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:304) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.internal.requests.Requester$WorkTask.handleResponse(Requester.java:442) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.internal.requests.Requester$WorkTask.access$300(Requester.java:378) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:245) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:157) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:140) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.internal.requests.Requester$WorkTask.execute(Requester.java:406) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.api.requests.SequentialRestRateLimiter$Bucket.execute(SequentialRestRateLimiter.java:477) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.api.requests.SequentialRestRateLimiter$Bucket.run(SequentialRestRateLimiter.java:517) ~[JDA-5.1.2.jar:5.1.2]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: net.dv8tion.jda.api.exceptions.ContextException
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:77) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:203) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573) ~[JDA-5.1.2.jar:5.1.2]
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:539) ~[JDA-5.1.2.jar:5.1.2]
	at mandarin.packpack.commands.Test.doThing(Test.java:22) ~[classes/:?]
```
```

**Comment by Xirado** [comment]
Already fixed in https://github.com/discord-jda/JDA/commit/e24fc593faa8f10fbbfe1344d7e0472816021254

**Comment by MandarinSmell** [comment]
Ah I see. Glad to hear that
